//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.2-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.08.02 at 12:04:00 VET 
//


package com.fedex.lacitd.cashcontrol.interfaces.importPayments;


/**
 * Java content class for anonymous complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/jwsdp-1.3/jaxb/bin/DataFeedOut.xsd line 162)
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}fedex_acc_nbr" minOccurs="0"/>
 *         &lt;element ref="{}cust_name" minOccurs="0"/>
 *         &lt;element ref="{}courier_id" minOccurs="0"/>
 *         &lt;element ref="{}chk_agent_id" minOccurs="0"/>
 *         &lt;element ref="{}pymt_tot_amt" minOccurs="0"/>
 *         &lt;element ref="{}pymt_doc_nbr" minOccurs="0"/>
 *         &lt;element ref="{}pymt_type" minOccurs="0"/>
 *         &lt;element ref="{}pymt_curr_cd" minOccurs="0"/>
 *         &lt;element ref="{}exch_rate" minOccurs="0"/>
 *         &lt;element ref="{}applied_to" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="num" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface PoaPaymentType {


    /**
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getPymtDocNbr();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setPymtDocNbr(java.lang.String value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link com.fedex.lacitd.cashcontrol.interfaces.importPayments.AppliedTo}
     *     {@link com.fedex.lacitd.cashcontrol.interfaces.importPayments.AppliedToType}
     */
    com.fedex.lacitd.cashcontrol.interfaces.importPayments.AppliedToType getAppliedTo();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link com.fedex.lacitd.cashcontrol.interfaces.importPayments.AppliedTo}
     *     {@link com.fedex.lacitd.cashcontrol.interfaces.importPayments.AppliedToType}
     */
    void setAppliedTo(com.fedex.lacitd.cashcontrol.interfaces.importPayments.AppliedToType value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigDecimal}
     */
    java.math.BigDecimal getPymtTotAmt();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link java.math.BigDecimal}
     */
    void setPymtTotAmt(java.math.BigDecimal value);

    /**
     * 
     */
    int getCourierId();

    /**
     * 
     */
    void setCourierId(int value);

    /**
     * 
     */
    int getPymtType();

    /**
     * 
     */
    void setPymtType(int value);

    /**
     * 
     */
    int getChkAgentId();

    /**
     * 
     */
    void setChkAgentId(int value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getPymtCurrCd();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setPymtCurrCd(java.lang.String value);

    /**
     * 
     */
    int getNum();

    /**
     * 
     */
    void setNum(int value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getCustName();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setCustName(java.lang.String value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getFedexAccNbr();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setFedexAccNbr(java.lang.String value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigDecimal}
     */
    java.math.BigDecimal getExchRate();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link java.math.BigDecimal}
     */
    void setExchRate(java.math.BigDecimal value);

}
