//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.2-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.05.13 at 11:11:44 VET 
//


package com.fedex.lacitd.cashcontrol.interfaces.rih.impl;

public class MDEResponseTypeImpl implements com.fedex.lacitd.cashcontrol.interfaces.rih.MDEResponseType, com.sun.xml.bind.JAXBObject, com.fedex.lacitd.cashcontrol.interfaces.rih.impl.runtime.UnmarshallableObject, com.fedex.lacitd.cashcontrol.interfaces.rih.impl.runtime.XMLSerializable, com.fedex.lacitd.cashcontrol.interfaces.rih.impl.runtime.ValidatableObject
{

    protected com.sun.xml.bind.util.ListImpl _Shipment = new com.sun.xml.bind.util.ListImpl(new java.util.ArrayList());
    public final static java.lang.Class version = (com.fedex.lacitd.cashcontrol.interfaces.rih.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (com.fedex.lacitd.cashcontrol.interfaces.rih.MDEResponseType.class);
    }

    public java.util.List getShipment() {
        return _Shipment;
    }

    public com.fedex.lacitd.cashcontrol.interfaces.rih.impl.runtime.UnmarshallingEventHandler createUnmarshaller(com.fedex.lacitd.cashcontrol.interfaces.rih.impl.runtime.UnmarshallingContext context) {
        return new com.fedex.lacitd.cashcontrol.interfaces.rih.impl.MDEResponseTypeImpl.Unmarshaller(context);
    }

    public void serializeBody(com.fedex.lacitd.cashcontrol.interfaces.rih.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx1 = 0;
        final int len1 = _Shipment.size();
        while (idx1 != len1) {
            if (_Shipment.get(idx1) instanceof javax.xml.bind.Element) {
                context.childAsBody(((com.sun.xml.bind.JAXBObject) _Shipment.get(idx1 ++)), "Shipment");
            } else {
                context.startElement("", "Shipment");
                int idx_0 = idx1;
                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Shipment.get(idx_0 ++)), "Shipment");
                context.endNamespaceDecls();
                int idx_1 = idx1;
                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Shipment.get(idx_1 ++)), "Shipment");
                context.endAttributes();
                context.childAsBody(((com.sun.xml.bind.JAXBObject) _Shipment.get(idx1 ++)), "Shipment");
                context.endElement();
            }
        }
    }

    public void serializeAttributes(com.fedex.lacitd.cashcontrol.interfaces.rih.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx1 = 0;
        final int len1 = _Shipment.size();
        while (idx1 != len1) {
            if (_Shipment.get(idx1) instanceof javax.xml.bind.Element) {
                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Shipment.get(idx1 ++)), "Shipment");
            } else {
                idx1 += 1;
            }
        }
    }

    public void serializeURIs(com.fedex.lacitd.cashcontrol.interfaces.rih.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        int idx1 = 0;
        final int len1 = _Shipment.size();
        while (idx1 != len1) {
            if (_Shipment.get(idx1) instanceof javax.xml.bind.Element) {
                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Shipment.get(idx1 ++)), "Shipment");
            } else {
                idx1 += 1;
            }
        }
    }

    public java.lang.Class getPrimaryInterface() {
        return (com.fedex.lacitd.cashcontrol.interfaces.rih.MDEResponseType.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000 com.sun.msv.grammar.OneOrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001ccom.s"
+"un.msv.grammar.UnaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expt\u0000 Lcom/sun/msv/gram"
+"mar/Expression;xr\u0000\u001ecom.sun.msv.grammar.Expression\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0003"
+"I\u0000\u000ecachedHashCodeL\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/lang/Boolean"
+";L\u0000\u000bexpandedExpq\u0000~\u0000\u0002xp\u0004\u00fd;\u00c7ppsr\u0000\u001dcom.sun.msv.grammar.ChoiceEx"
+"p\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004e"
+"xp1q\u0000~\u0000\u0002L\u0000\u0004exp2q\u0000~\u0000\u0002xq\u0000~\u0000\u0003\u0004\u00fd;\u00c4ppsr\u0000\'com.sun.msv.grammar.trex"
+".ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameClasst\u0000\u001fLcom/sun/msv/gramma"
+"r/NameClass;xr\u0000\u001ecom.sun.msv.grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001a"
+"ignoreUndeclaredAttributesL\u0000\fcontentModelq\u0000~\u0000\u0002xq\u0000~\u0000\u0003\u0001>\n\u00dcpp\u0000s"
+"q\u0000~\u0000\u0006\u0001>\n\u00d1ppsq\u0000~\u0000\u0000\u0001>\n\u00c6sr\u0000\u0011java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valu"
+"exp\u0000psr\u0000 com.sun.msv.grammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000"
+"~\u0000\u0002L\u0000\tnameClassq\u0000~\u0000\nxq\u0000~\u0000\u0003\u0001>\n\u00c3q\u0000~\u0000\u0010psr\u00002com.sun.msv.grammar."
+"Expression$AnyStringExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003\u0000\u0000\u0000\bsq\u0000~\u0000\u000f\u0001ps"
+"r\u0000 com.sun.msv.grammar.AnyNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun.ms"
+"v.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpsr\u00000com.sun.msv.grammar.Expr"
+"ession$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003\u0000\u0000\u0000\tq\u0000~\u0000\u0015psr\u0000#com.s"
+"un.msv.grammar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNamet\u0000\u0012Ljav"
+"a/lang/String;L\u0000\fnamespaceURIq\u0000~\u0000\u001cxq\u0000~\u0000\u0017t\u00004com.fedex.lacitd."
+"cashcontrol.interfaces.rih.Shipmentt\u0000+http://java.sun.com/ja"
+"xb/xjc/dummy-elementssq\u0000~\u0000\t\u0003\u00bf0\u00e6pp\u0000sr\u0000\u001fcom.sun.msv.grammar.Se"
+"quenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0007\u0003\u00bf0\u00dbppsq\u0000~\u0000\t\u0001>\n\u00dcpp\u0000sq\u0000~\u0000\u0006\u0001>\n\u00d1ppsq\u0000"
+"~\u0000\u0000\u0001>\n\u00c6q\u0000~\u0000\u0010psq\u0000~\u0000\u0011\u0001>\n\u00c3q\u0000~\u0000\u0010pq\u0000~\u0000\u0014q\u0000~\u0000\u0018q\u0000~\u0000\u001asq\u0000~\u0000\u001bt\u00008com.fed"
+"ex.lacitd.cashcontrol.interfaces.rih.ShipmentTypeq\u0000~\u0000\u001fsq\u0000~\u0000\u0006"
+"\u0002\u0081%\u00fappsq\u0000~\u0000\u0011\u0002\u0081%\u00efq\u0000~\u0000\u0010psr\u0000\u001bcom.sun.msv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/relaxng/datatype/Datatype;L\u0000\u0006exceptq\u0000~\u0000\u0002L\u0000\u0004"
+"namet\u0000\u001dLcom/sun/msv/util/StringPair;xq\u0000~\u0000\u0003\u0001\u009f7Fppsr\u0000\"com.sun."
+"msv.datatype.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000*com.sun.msv.datatyp"
+"e.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.datatype.x"
+"sd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.datatype.xsd.XSDat"
+"atypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUriq\u0000~\u0000\u001cL\u0000\btypeNameq\u0000~\u0000\u001cL\u0000\nw"
+"hiteSpacet\u0000.Lcom/sun/msv/datatype/xsd/WhiteSpaceProcessor;xp"
+"t\u0000 http://www.w3.org/2001/XMLSchemat\u0000\u0005QNamesr\u00005com.sun.msv.d"
+"atatype.xsd.WhiteSpaceProcessor$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.s"
+"un.msv.datatype.xsd.WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpsr\u00000com."
+"sun.msv.grammar.Expression$NullSetExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000"
+"\u0003\u0000\u0000\u0000\nppsr\u0000\u001bcom.sun.msv.util.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNam"
+"eq\u0000~\u0000\u001cL\u0000\fnamespaceURIq\u0000~\u0000\u001cxpq\u0000~\u00006q\u0000~\u00005sq\u0000~\u0000\u001bt\u0000\u0004typet\u0000)http:/"
+"/www.w3.org/2001/XMLSchema-instanceq\u0000~\u0000\u001asq\u0000~\u0000\u001bt\u0000\bShipmentt\u0000\u0000"
+"sr\u0000\"com.sun.msv.grammar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTable"
+"t\u0000/Lcom/sun/msv/grammar/ExpressionPool$ClosedHash;xpsr\u0000-com."
+"sun.msv.grammar.ExpressionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0002\u0000\u0004I\u0000\u0005count"
+"I\u0000\tthresholdL\u0000\u0006parentq\u0000~\u0000E[\u0000\u0005tablet\u0000![Lcom/sun/msv/grammar/E"
+"xpression;xp\u0000\u0000\u0000\b\u0000\u0000\u00009pur\u0000![Lcom.sun.msv.grammar.Expression;\u00d68"
+"D\u00c3]\u00ad\u00a7\n\u0002\u0000\u0000xp\u0000\u0000\u0000\u00bfpppppppppppppppppq\u0000~\u0000)ppppppppppppppppppppppp"
+"pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp"
+"pppppppppppppppppppppppppppppppppppppppq\u0000~\u0000\u000eq\u0000~\u0000%pppppppppq\u0000"
+"~\u0000\rq\u0000~\u0000$pppppppppppppppq\u0000~\u0000\bppq\u0000~\u0000\u0005ppppppppppppq\u0000~\u0000\"pppppp"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends com.fedex.lacitd.cashcontrol.interfaces.rih.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(com.fedex.lacitd.cashcontrol.interfaces.rih.impl.runtime.UnmarshallingContext context) {
            super(context, "----");
        }

        protected Unmarshaller(com.fedex.lacitd.cashcontrol.interfaces.rih.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return com.fedex.lacitd.cashcontrol.interfaces.rih.impl.MDEResponseTypeImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  0 :
                        if (("Shipment" == ___local)&&("" == ___uri)) {
                            _Shipment.add(((com.fedex.lacitd.cashcontrol.interfaces.rih.impl.ShipmentImpl) spawnChildFromEnterElement((com.fedex.lacitd.cashcontrol.interfaces.rih.impl.ShipmentImpl.class), 1, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("Shipment" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 2;
                            return ;
                        }
                        break;
                    case  1 :
                        if (("Shipment" == ___local)&&("" == ___uri)) {
                            _Shipment.add(((com.fedex.lacitd.cashcontrol.interfaces.rih.impl.ShipmentImpl) spawnChildFromEnterElement((com.fedex.lacitd.cashcontrol.interfaces.rih.impl.ShipmentImpl.class), 1, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("Shipment" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 2;
                            return ;
                        }
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  2 :
                        if (("awbNbr" == ___local)&&("" == ___uri)) {
                            _Shipment.add(((com.fedex.lacitd.cashcontrol.interfaces.rih.impl.ShipmentTypeImpl) spawnChildFromEnterElement((com.fedex.lacitd.cashcontrol.interfaces.rih.impl.ShipmentTypeImpl.class), 3, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("origLocation" == ___local)&&("" == ___uri)) {
                            _Shipment.add(((com.fedex.lacitd.cashcontrol.interfaces.rih.impl.ShipmentTypeImpl) spawnChildFromEnterElement((com.fedex.lacitd.cashcontrol.interfaces.rih.impl.ShipmentTypeImpl.class), 3, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("destLocation" == ___local)&&("" == ___uri)) {
                            _Shipment.add(((com.fedex.lacitd.cashcontrol.interfaces.rih.impl.ShipmentTypeImpl) spawnChildFromEnterElement((com.fedex.lacitd.cashcontrol.interfaces.rih.impl.ShipmentTypeImpl.class), 3, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("shipDt" == ___local)&&("" == ___uri)) {
                            _Shipment.add(((com.fedex.lacitd.cashcontrol.interfaces.rih.impl.ShipmentTypeImpl) spawnChildFromEnterElement((com.fedex.lacitd.cashcontrol.interfaces.rih.impl.ShipmentTypeImpl.class), 3, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("origCountry" == ___local)&&("" == ___uri)) {
                            _Shipment.add(((com.fedex.lacitd.cashcontrol.interfaces.rih.impl.ShipmentTypeImpl) spawnChildFromEnterElement((com.fedex.lacitd.cashcontrol.interfaces.rih.impl.ShipmentTypeImpl.class), 3, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("destCountry" == ___local)&&("" == ___uri)) {
                            _Shipment.add(((com.fedex.lacitd.cashcontrol.interfaces.rih.impl.ShipmentTypeImpl) spawnChildFromEnterElement((com.fedex.lacitd.cashcontrol.interfaces.rih.impl.ShipmentTypeImpl.class), 3, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("freightChargeAmt" == ___local)&&("" == ___uri)) {
                            _Shipment.add(((com.fedex.lacitd.cashcontrol.interfaces.rih.impl.ShipmentTypeImpl) spawnChildFromEnterElement((com.fedex.lacitd.cashcontrol.interfaces.rih.impl.ShipmentTypeImpl.class), 3, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("shipperCompany" == ___local)&&("" == ___uri)) {
                            _Shipment.add(((com.fedex.lacitd.cashcontrol.interfaces.rih.impl.ShipmentTypeImpl) spawnChildFromEnterElement((com.fedex.lacitd.cashcontrol.interfaces.rih.impl.ShipmentTypeImpl.class), 3, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        if (("shipperNm" == ___local)&&("" == ___uri)) {
                            _Shipment.add(((com.fedex.lacitd.cashcontrol.interfaces.rih.impl.ShipmentTypeImpl) spawnChildFromEnterElement((com.fedex.lacitd.cashcontrol.interfaces.rih.impl.ShipmentTypeImpl.class), 3, ___uri, ___local, ___qname, __atts)));
                            return ;
                        }
                        _Shipment.add(((com.fedex.lacitd.cashcontrol.interfaces.rih.impl.ShipmentTypeImpl) spawnChildFromEnterElement((com.fedex.lacitd.cashcontrol.interfaces.rih.impl.ShipmentTypeImpl.class), 3, ___uri, ___local, ___qname, __atts)));
                        return ;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        if (("Shipment" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 1;
                            return ;
                        }
                        break;
                    case  1 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  2 :
                        _Shipment.add(((com.fedex.lacitd.cashcontrol.interfaces.rih.impl.ShipmentTypeImpl) spawnChildFromLeaveElement((com.fedex.lacitd.cashcontrol.interfaces.rih.impl.ShipmentTypeImpl.class), 3, ___uri, ___local, ___qname)));
                        return ;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  1 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                    case  2 :
                        _Shipment.add(((com.fedex.lacitd.cashcontrol.interfaces.rih.impl.ShipmentTypeImpl) spawnChildFromEnterAttribute((com.fedex.lacitd.cashcontrol.interfaces.rih.impl.ShipmentTypeImpl.class), 3, ___uri, ___local, ___qname)));
                        return ;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  1 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                    case  2 :
                        _Shipment.add(((com.fedex.lacitd.cashcontrol.interfaces.rih.impl.ShipmentTypeImpl) spawnChildFromLeaveAttribute((com.fedex.lacitd.cashcontrol.interfaces.rih.impl.ShipmentTypeImpl.class), 3, ___uri, ___local, ___qname)));
                        return ;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  1 :
                            revertToParentFromText(value);
                            return ;
                        case  2 :
                            _Shipment.add(((com.fedex.lacitd.cashcontrol.interfaces.rih.impl.ShipmentTypeImpl) spawnChildFromText((com.fedex.lacitd.cashcontrol.interfaces.rih.impl.ShipmentTypeImpl.class), 3, value)));
                            return ;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

    }

}
