package com.fedex.lacitd.cashcontrol.biztier.facades;


/**
 * Created 09-07-2002 03:34:14 PM
 * Code generated by the Forte For Java EJB Builder
 *
 * @author ccardenas
 */

public interface FTCFacadeHome extends javax.ejb.EJBHome {

    public FTCFacade create() throws java.rmi.RemoteException, javax.ejb.CreateException;

}
