package com.fedex.lacitd.cashcontrol.datatier.dao;


/**
 * Created Apr 23, 2003 5:01:28 PM
 * Code generated by the Forte For Java EJB Builder
 *
 * @author ccardenas
 */

public interface AdminDaoLocalHome extends javax.ejb.EJBLocalHome {

    public AdminDaoLocal create() throws javax.ejb.CreateException;

}
