//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.2-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.08.02 at 12:04:00 VET 
//


package com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl;

public class PoaPaymentImpl
    extends com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentTypeImpl
    implements com.fedex.lacitd.cashcontrol.interfaces.importPayments.PoaPayment, com.sun.xml.bind.RIElement, com.sun.xml.bind.JAXBObject, com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.runtime.UnmarshallableObject, com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.runtime.XMLSerializable, com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.runtime.ValidatableObject
{

    public final static java.lang.Class version = (com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (com.fedex.lacitd.cashcontrol.interfaces.importPayments.PoaPayment.class);
    }

    public java.lang.String ____jaxb_ri____getNamespaceURI() {
        return "";
    }

    public java.lang.String ____jaxb_ri____getLocalName() {
        return "poa_payment";
    }

    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.runtime.UnmarshallingEventHandler createUnmarshaller(com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.runtime.UnmarshallingContext context) {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentImpl.Unmarshaller(context);
    }

    public void serializeBody(com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        context.startElement("", "poa_payment");
        super.serializeURIs(context);
        context.endNamespaceDecls();
        super.serializeAttributes(context);
        context.endAttributes();
        super.serializeBody(context);
        context.endElement();
    }

    public void serializeAttributes(com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public void serializeURIs(com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public java.lang.Class getPrimaryInterface() {
        return (com.fedex.lacitd.cashcontrol.interfaces.importPayments.PoaPayment.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\'com.sun.msv.grammar.trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000"
+"\tnameClasst\u0000\u001fLcom/sun/msv/grammar/NameClass;xr\u0000\u001ecom.sun.msv."
+"grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000"
+"\fcontentModelt\u0000 Lcom/sun/msv/grammar/Expression;xr\u0000\u001ecom.sun."
+"msv.grammar.Expression\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0003I\u0000\u000ecachedHashCodeL\u0000\u0013epsilon"
+"Reducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000bexpandedExpq\u0000~\u0000\u0003xp2\u00c6\u000f\u000bp"
+"p\u0000sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun."
+"msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1q\u0000~\u0000\u0003L\u0000\u0004exp2q\u0000~\u0000\u0003xq\u0000~"
+"\u0000\u00042\u00c6\u000f\u0000ppsq\u0000~\u0000\u00070\n\u00bc\u00cbppsq\u0000~\u0000\u0007,\u0086\u0006\u0083ppsq\u0000~\u0000\u0007%\u00b3X\u00f6ppsq\u0000~\u0000\u0007 \u009a\u00dc\'ppsq\u0000~"
+"\u0000\u0007\u001c\u00b1\u008b\u00b9ppsq\u0000~\u0000\u0007\u0018\u00ae\u0080\nppsq\u0000~\u0000\u0007\u0014\u0019\u00ed\u00d0ppsq\u0000~\u0000\u0007\u0010\n\u00e2\u00a5ppsq\u0000~\u0000\u0007\u000b\u0014\u00b6]ppsq\u0000~"
+"\u0000\u0007\u0006{\u00c9\u0006ppsr\u0000\u001dcom.sun.msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\b\u0003N"
+"\u009dYppsq\u0000~\u0000\u0000\u0003N\u009dNsr\u0000\u0011java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000p\u0000s"
+"q\u0000~\u0000\u0007\u0003N\u009dCppsr\u0000\u001bcom.sun.msv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000"
+"\u001fLorg/relaxng/datatype/Datatype;L\u0000\u0006exceptq\u0000~\u0000\u0003L\u0000\u0004namet\u0000\u001dLcom"
+"/sun/msv/util/StringPair;xq\u0000~\u0000\u0004\u0001>\n\u00cappsr\u0000#com.sun.msv.datatyp"
+"e.xsd.StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlwaysValidxr\u0000*com.sun.msv.d"
+"atatype.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.data"
+"type.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.datatype.xsd"
+".XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUrit\u0000\u0012Ljava/lang/Strin"
+"g;L\u0000\btypeNameq\u0000~\u0000\"L\u0000\nwhiteSpacet\u0000.Lcom/sun/msv/datatype/xsd/"
+"WhiteSpaceProcessor;xpt\u0000 http://www.w3.org/2001/XMLSchemat\u0000\u0006"
+"stringsr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcessor$Prese"
+"rve\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.datatype.xsd.WhiteSpaceProcess"
+"or\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xp\u0001sr\u00000com.sun.msv.grammar.Expression$NullSetEx"
+"pression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0004\u0000\u0000\u0000\nppsr\u0000\u001bcom.sun.msv.util.StringPa"
+"ir\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\"L\u0000\fnamespaceURIq\u0000~\u0000\"xpq\u0000~\u0000&q\u0000~"
+"\u0000%sq\u0000~\u0000\u0014\u0002\u0010\u0092tppsr\u0000 com.sun.msv.grammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000"
+"\u0002L\u0000\u0003expq\u0000~\u0000\u0003L\u0000\tnameClassq\u0000~\u0000\u0001xq\u0000~\u0000\u0004\u0002\u0010\u0092iq\u0000~\u0000\u0018psq\u0000~\u0000\u001a\u0001\u00e9\u0003\u00e5ppsr\u0000"
+"\"com.sun.msv.datatype.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u001fq\u0000~\u0000%t\u0000\u0005"
+"QNamesr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcessor$Collap"
+"se\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000(q\u0000~\u0000+sq\u0000~\u0000,q\u0000~\u00004q\u0000~\u0000%sr\u0000#com.sun.msv.gram"
+"mar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\"L\u0000\fnamespaceU"
+"RIq\u0000~\u0000\"xr\u0000\u001dcom.sun.msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpt\u0000\u0004type"
+"t\u0000)http://www.w3.org/2001/XMLSchema-instancesr\u00000com.sun.msv."
+"grammar.Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0004\u0000\u0000\u0000\tsq\u0000"
+"~\u0000\u0017\u0001psq\u0000~\u00008t\u0000\rfedex_acc_nbrt\u0000\u0000q\u0000~\u0000>sq\u0000~\u0000\u0014\u0003-+\u00a8ppsq\u0000~\u0000\u0000\u0003-+\u009dq\u0000~"
+"\u0000\u0018p\u0000sq\u0000~\u0000\u0007\u0003-+\u0092ppq\u0000~\u0000\u001dsq\u0000~\u0000\u0014\u0001\u00ef \u00c3ppsq\u0000~\u0000/\u0001\u00ef \u00b8q\u0000~\u0000\u0018pq\u0000~\u00001sq\u0000~\u00008"
+"q\u0000~\u0000;q\u0000~\u0000<q\u0000~\u0000>sq\u0000~\u00008t\u0000\tcust_nameq\u0000~\u0000Bq\u0000~\u0000>sq\u0000~\u0000\u0014\u0004\u0098\u00edRppsq\u0000~\u0000"
+"\u0000\u0004\u0098\u00edGq\u0000~\u0000\u0018p\u0000sq\u0000~\u0000\u0007\u0004\u0098\u00ed<ppsq\u0000~\u0000\u001a\u0001\u00a6h_ppsr\u0000 com.sun.msv.datatype"
+".xsd.IntType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000+com.sun.msv.datatype.xsd.IntegerD"
+"erivedType\u0099\u00f1]\u0090&6k\u00be\u0002\u0000\u0001L\u0000\nbaseFacetst\u0000)Lcom/sun/msv/datatype/x"
+"sd/XSDatatypeImpl;xq\u0000~\u0000\u001fq\u0000~\u0000%t\u0000\u0003intq\u0000~\u00006sr\u0000*com.sun.msv.data"
+"type.xsd.MaxInclusiveFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000#com.sun.msv.datatyp"
+"e.xsd.RangeFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\nlimitValuet\u0000\u0012Ljava/lang/Object"
+";xr\u00009com.sun.msv.datatype.xsd.DataTypeWithValueConstraintFac"
+"et\"\u00a7Ro\u00ca\u00c7\u008aT\u0002\u0000\u0000xr\u0000*com.sun.msv.datatype.xsd.DataTypeWithFacet\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0005Z\u0000\fisFacetFixedZ\u0000\u0012needValueCheckFlagL\u0000\bbaseTypeq\u0000~"
+"\u0000QL\u0000\fconcreteTypet\u0000\'Lcom/sun/msv/datatype/xsd/ConcreteType;L"
+"\u0000\tfacetNameq\u0000~\u0000\"xq\u0000~\u0000!ppq\u0000~\u00006\u0000\u0001sr\u0000*com.sun.msv.datatype.xsd."
+"MinInclusiveFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000Uppq\u0000~\u00006\u0000\u0000sr\u0000!com.sun.msv.d"
+"atatype.xsd.LongType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000Pq\u0000~\u0000%t\u0000\u0004longq\u0000~\u00006sq\u0000~\u0000T"
+"ppq\u0000~\u00006\u0000\u0001sq\u0000~\u0000[ppq\u0000~\u00006\u0000\u0000sr\u0000$com.sun.msv.datatype.xsd.Integer"
+"Type\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000Pq\u0000~\u0000%t\u0000\u0007integerq\u0000~\u00006sr\u0000,com.sun.msv.dat"
+"atype.xsd.FractionDigitsFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001I\u0000\u0005scalexr\u0000;com.sun."
+"msv.datatype.xsd.DataTypeWithLexicalConstraintFacetT\u0090\u001c>\u001azb\u00ea\u0002"
+"\u0000\u0000xq\u0000~\u0000Xppq\u0000~\u00006\u0001\u0000sr\u0000#com.sun.msv.datatype.xsd.NumberType\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u001fq\u0000~\u0000%t\u0000\u0007decimalq\u0000~\u00006q\u0000~\u0000it\u0000\u000efractionDigits\u0000\u0000\u0000\u0000q"
+"\u0000~\u0000ct\u0000\fminInclusivesr\u0000\u000ejava.lang.Long;\u008b\u00e4\u0090\u00cc\u008f#\u00df\u0002\u0000\u0001J\u0000\u0005valuexr\u0000\u0010"
+"java.lang.Number\u0086\u00ac\u0095\u001d\u000b\u0094\u00e0\u008b\u0002\u0000\u0000xp\u0080\u0000\u0000\u0000\u0000\u0000\u0000\u0000q\u0000~\u0000ct\u0000\fmaxInclusivesq\u0000"
+"~\u0000m\u007f\u00ff\u00ff\u00ff\u00ff\u00ff\u00ff\u00ffq\u0000~\u0000^q\u0000~\u0000lsr\u0000\u0011java.lang.Integer\u0012\u00e2\u00a0\u00a4\u00f7\u0081\u00878\u0002\u0000\u0001I\u0000\u0005valu"
+"exq\u0000~\u0000n\u0080\u0000\u0000\u0000q\u0000~\u0000^q\u0000~\u0000psq\u0000~\u0000r\u007f\u00ff\u00ff\u00ffq\u0000~\u0000+sq\u0000~\u0000,q\u0000~\u0000Sq\u0000~\u0000%sq\u0000~\u0000\u0014\u0002\u00f2"
+"\u0084\u00d8ppsq\u0000~\u0000/\u0002\u00f2\u0084\u00cdq\u0000~\u0000\u0018pq\u0000~\u00001sq\u0000~\u00008q\u0000~\u0000;q\u0000~\u0000<q\u0000~\u0000>sq\u0000~\u00008t\u0000\ncouri"
+"er_idq\u0000~\u0000Bq\u0000~\u0000>sq\u0000~\u0000\u0014\u0004\u00f6,Cppsq\u0000~\u0000\u0000\u0004\u00f6,8q\u0000~\u0000\u0018p\u0000sq\u0000~\u0000\u0007\u0004\u00f6,-ppq\u0000~\u0000"
+"Nsq\u0000~\u0000\u0014\u0003O\u00c3\u00c9ppsq\u0000~\u0000/\u0003O\u00c3\u00beq\u0000~\u0000\u0018pq\u0000~\u00001sq\u0000~\u00008q\u0000~\u0000;q\u0000~\u0000<q\u0000~\u0000>sq\u0000~\u0000"
+"8t\u0000\fchk_agent_idq\u0000~\u0000Bq\u0000~\u0000>sq\u0000~\u0000\u0014\u0004\u000f\u000b&ppsq\u0000~\u0000\u0000\u0004\u000f\u000b\u001bq\u0000~\u0000\u0018p\u0000sq\u0000~\u0000"
+"\u0007\u0004\u000f\u000b\u0010ppsq\u0000~\u0000\u001a\u0001\u00d8\u00c58ppq\u0000~\u0000iq\u0000~\u0000+sq\u0000~\u0000,q\u0000~\u0000jq\u0000~\u0000%sq\u0000~\u0000\u0014\u00026E\u00d3ppsq\u0000"
+"~\u0000/\u00026E\u00c8q\u0000~\u0000\u0018pq\u0000~\u00001sq\u0000~\u00008q\u0000~\u0000;q\u0000~\u0000<q\u0000~\u0000>sq\u0000~\u00008t\u0000\fpymt_tot_amt"
+"q\u0000~\u0000Bq\u0000~\u0000>sq\u0000~\u0000\u0014\u0004\u0094\u00925ppsq\u0000~\u0000\u0000\u0004\u0094\u0092*q\u0000~\u0000\u0018p\u0000sq\u0000~\u0000\u0007\u0004\u0094\u0092\u001fppq\u0000~\u0000\u001dsq\u0000~"
+"\u0000\u0014\u0003V\u0087Pppsq\u0000~\u0000/\u0003V\u0087Eq\u0000~\u0000\u0018pq\u0000~\u00001sq\u0000~\u00008q\u0000~\u0000;q\u0000~\u0000<q\u0000~\u0000>sq\u0000~\u00008t\u0000\fp"
+"ymt_doc_nbrq\u0000~\u0000Bq\u0000~\u0000>sq\u0000~\u0000\u0014\u0004\u0003\u000b\u00aappsq\u0000~\u0000\u0000\u0004\u0003\u000b\u009fq\u0000~\u0000\u0018p\u0000sq\u0000~\u0000\u0007\u0004\u0003\u000b\u0094"
+"ppq\u0000~\u0000Nsq\u0000~\u0000\u0014\u0002\\\u00a30ppsq\u0000~\u0000/\u0002\\\u00a3%q\u0000~\u0000\u0018pq\u0000~\u00001sq\u0000~\u00008q\u0000~\u0000;q\u0000~\u0000<q\u0000~\u0000"
+">sq\u0000~\u00008t\u0000\tpymt_typeq\u0000~\u0000Bq\u0000~\u0000>sq\u0000~\u0000\u0014\u0003\u00e9Pippsq\u0000~\u0000\u0000\u0003\u00e9P^q\u0000~\u0000\u0018p\u0000sq"
+"\u0000~\u0000\u0007\u0003\u00e9PSppq\u0000~\u0000\u001dsq\u0000~\u0000\u0014\u0002\u00abE\u0084ppsq\u0000~\u0000/\u0002\u00abEyq\u0000~\u0000\u0018pq\u0000~\u00001sq\u0000~\u00008q\u0000~\u0000;q"
+"\u0000~\u0000<q\u0000~\u0000>sq\u0000~\u00008t\u0000\fpymt_curr_cdq\u0000~\u0000Bq\u0000~\u0000>sq\u0000~\u0000\u0014\u0005\u0018|\u00cappsq\u0000~\u0000\u0000\u0005\u0018"
+"|\u00bfq\u0000~\u0000\u0018p\u0000sq\u0000~\u0000\u0007\u0005\u0018|\u00b4ppq\u0000~\u0000\u0086sq\u0000~\u0000\u0014\u0003?\u00b7wppsq\u0000~\u0000/\u0003?\u00b7lq\u0000~\u0000\u0018pq\u0000~\u00001s"
+"q\u0000~\u00008q\u0000~\u0000;q\u0000~\u0000<q\u0000~\u0000>sq\u0000~\u00008t\u0000\texch_rateq\u0000~\u0000Bq\u0000~\u0000>sq\u0000~\u0000\u0014\u0006\u00d2\u00ad\u0088pp"
+"sq\u0000~\u0000\u0014\u0006\u00d2\u00ad}q\u0000~\u0000\u0018psq\u0000~\u0000\u0000\u0001\u008e\u00d7\u009cq\u0000~\u0000\u0018p\u0000sq\u0000~\u0000\u0014\u0001\u008e\u00d7\u0091ppsr\u0000 com.sun.msv"
+".grammar.OneOrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001ccom.sun.msv.grammar.Unar"
+"yExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000~\u0000\u0003xq\u0000~\u0000\u0004\u0001\u008e\u00d7\u0086q\u0000~\u0000\u0018psq\u0000~\u0000/\u0001\u008e\u00d7\u0083q\u0000~\u0000\u0018psr"
+"\u00002com.sun.msv.grammar.Expression$AnyStringExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001"
+"\u0002\u0000\u0000xq\u0000~\u0000\u0004\u0000\u0000\u0000\bq\u0000~\u0000?psr\u0000 com.sun.msv.grammar.AnyNameClass\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u00009q\u0000~\u0000>sq\u0000~\u00008t\u0000@com.fedex.lacitd.cashcontrol.inter"
+"faces.importPayments.AppliedTot\u0000+http://java.sun.com/jaxb/xj"
+"c/dummy-elementssq\u0000~\u0000\u0000\u0005C\u00d5\u00dfq\u0000~\u0000\u0018p\u0000sq\u0000~\u0000\u0007\u0005C\u00d5\u00d4ppsq\u0000~\u0000\u0000\u0001\u008e\u00d7\u009cpp\u0000sq"
+"\u0000~\u0000\u0014\u0001\u008e\u00d7\u0091ppsq\u0000~\u0000\u00b1\u0001\u008e\u00d7\u0086q\u0000~\u0000\u0018psq\u0000~\u0000/\u0001\u008e\u00d7\u0083q\u0000~\u0000\u0018pq\u0000~\u0000\u00b6q\u0000~\u0000\u00b8q\u0000~\u0000>sq\u0000"
+"~\u00008t\u0000Dcom.fedex.lacitd.cashcontrol.interfaces.importPayments"
+".AppliedToTypeq\u0000~\u0000\u00bbsq\u0000~\u0000\u0014\u0003\u00b4\u00fe3ppsq\u0000~\u0000/\u0003\u00b4\u00fe(q\u0000~\u0000\u0018pq\u0000~\u00001sq\u0000~\u00008q\u0000"
+"~\u0000;q\u0000~\u0000<q\u0000~\u0000>sq\u0000~\u00008t\u0000\napplied_toq\u0000~\u0000Bq\u0000~\u0000>sq\u0000~\u0000\u0014\u0003\u0084\u00b6Cppsq\u0000~\u0000/"
+"\u0003\u0084\u00b68q\u0000~\u0000\u0018pq\u0000~\u0000Nsq\u0000~\u00008t\u0000\u0003numq\u0000~\u0000Bq\u0000~\u0000>sq\u0000~\u0000\u0014\u0002\u00bbR0ppsq\u0000~\u0000/\u0002\u00bbR%q"
+"\u0000~\u0000\u0018pq\u0000~\u00001sq\u0000~\u00008q\u0000~\u0000;q\u0000~\u0000<q\u0000~\u0000>sq\u0000~\u00008t\u0000\u000bpoa_paymentq\u0000~\u0000Bsr\u0000\""
+"com.sun.msv.grammar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/L"
+"com/sun/msv/grammar/ExpressionPool$ClosedHash;xpsr\u0000-com.sun."
+"msv.grammar.ExpressionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0002\u0000\u0004I\u0000\u0005countI\u0000\tt"
+"hresholdL\u0000\u0006parentq\u0000~\u0000\u00d3[\u0000\u0005tablet\u0000![Lcom/sun/msv/grammar/Expre"
+"ssion;xp\u0000\u0000\u00000\u0000\u0000\u00009pur\u0000![Lcom.sun.msv.grammar.Expression;\u00d68D\u00c3]\u00ad"
+"\u00a7\n\u0002\u0000\u0000xp\u0000\u0000\u0000\u00bfpppppppppppq\u0000~\u0000\u0083pppppq\u0000~\u0000\rq\u0000~\u0000\u008dppppppppq\u0000~\u0000}ppppq"
+"\u0000~\u0000\u00a7pppq\u0000~\u0000\u0097pq\u0000~\u0000\u0090q\u0000~\u0000\u009fq\u0000~\u0000\u0013q\u0000~\u0000\u0011pppppppq\u0000~\u0000{q\u0000~\u0000\u000bpppq\u0000~\u0000\u00a5pp"
+"q\u0000~\u0000Eq\u0000~\u0000\u0010q\u0000~\u0000\u0095q\u0000~\u0000\u009dq\u0000~\u0000\tpq\u0000~\u0000\u00cdppppppppppppq\u0000~\u0000\fpq\u0000~\u0000~q\u0000~\u0000Cq"
+"\u0000~\u0000\u000fq\u0000~\u0000\u00a0pppppq\u0000~\u0000\u0098pppppppppppq\u0000~\u0000Fpppppppppppq\u0000~\u0000Mppppppppp"
+"ppppq\u0000~\u0000\u0019pq\u0000~\u0000\u00c9pppppq\u0000~\u0000Kppppppppq\u0000~\u0000\u0088q\u0000~\u0000\u000epppq\u0000~\u0000\u0015pq\u0000~\u0000\u00aeppq"
+"\u0000~\u0000\u00b3q\u0000~\u0000\u00c0q\u0000~\u0000\u00bdpppppq\u0000~\u0000\u00adpq\u0000~\u0000vq\u0000~\u0000\u00b0q\u0000~\u0000\u00bfq\u0000~\u0000\u00c4pq\u0000~\u0000.ppppppppp"
+"pq\u0000~\u0000\u0012pq\u0000~\u0000\u0085pq\u0000~\u0000\nppq\u0000~\u0000\u00a8pq\u0000~\u0000\u008fppp"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.runtime.UnmarshallingContext context) {
            super(context, "----");
        }

        protected Unmarshaller(com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  0 :
                        if (("poa_payment" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 1;
                            return ;
                        }
                        break;
                    case  1 :
                        attIdx = context.getAttribute("", "num");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("fedex_acc_nbr" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterElement((((com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentTypeImpl)com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("cust_name" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterElement((((com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentTypeImpl)com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("courier_id" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterElement((((com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentTypeImpl)com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("chk_agent_id" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterElement((((com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentTypeImpl)com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("pymt_tot_amt" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterElement((((com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentTypeImpl)com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("pymt_doc_nbr" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterElement((((com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentTypeImpl)com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("pymt_type" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterElement((((com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentTypeImpl)com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("pymt_curr_cd" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterElement((((com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentTypeImpl)com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("exch_rate" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterElement((((com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentTypeImpl)com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("applied_to" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterElement((((com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentTypeImpl)com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("applied_to" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterElement((((com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentTypeImpl)com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        spawnHandlerFromEnterElement((((com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentTypeImpl)com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                        return ;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  2 :
                        if (("poa_payment" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  1 :
                        attIdx = context.getAttribute("", "num");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        spawnHandlerFromLeaveElement((((com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentTypeImpl)com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname);
                        return ;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                    case  1 :
                        if (("num" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterAttribute((((com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentTypeImpl)com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname);
                            return ;
                        }
                        spawnHandlerFromEnterAttribute((((com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentTypeImpl)com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname);
                        return ;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                    case  1 :
                        attIdx = context.getAttribute("", "num");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        spawnHandlerFromLeaveAttribute((((com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentTypeImpl)com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname);
                        return ;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  3 :
                            revertToParentFromText(value);
                            return ;
                        case  1 :
                            attIdx = context.getAttribute("", "num");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            spawnHandlerFromText((((com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentTypeImpl)com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentImpl.this).new Unmarshaller(context)), 2, value);
                            return ;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

    }

}
