package com.fedex.lacitd.cashcontrol.datatier.dao;


/**
 * Created 18/11/2003 16:00:06
 * Code generated by the Sun ONE Studio EJB Builder
 *
 * @author ccardenas
 */

public interface PrepPoaDaoHome extends javax.ejb.EJBHome {

    public com.fedex.lacitd.cashcontrol.datatier.dao.PrepPoaDao create()
            throws javax.ejb.CreateException, java.rmi.RemoteException;

}
