//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.2-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.08.02 at 12:04:00 VET 
//


package com.fedex.lacitd.cashcontrol.interfaces.importPayments;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.fedex.lacitd.cashcontrol.interfaces.importPayments package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
public class ObjectFactory
    extends com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.runtime.DefaultJAXBContextImpl
{

    private static java.util.HashMap defaultImplementations = new java.util.HashMap();
    private static java.util.HashMap rootTagMap = new java.util.HashMap();
    public final static com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.runtime.GrammarInfo grammarInfo = new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.runtime.GrammarInfoImpl(rootTagMap, defaultImplementations, (com.fedex.lacitd.cashcontrol.interfaces.importPayments.ObjectFactory.class));
    public final static java.lang.Class version = (com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.JAXBVersion.class);

    static {
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.OtherPaymentType.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.OtherPaymentTypeImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.PrepaidPayments.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PrepaidPaymentsImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.RecAncChrgAmt.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.RecAncChrgAmtImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.RodPayments.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.RodPaymentsImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.OacPaymentsType.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.OacPaymentsTypeImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.FedexAccNbr.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.FedexAccNbrImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.GroundPaymentsType.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.GroundPaymentsTypeImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.OtherPayment.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.OtherPaymentImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.RecRodAmt.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.RecRodAmtImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.PrepaidPayment.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PrepaidPaymentImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.InvNbr.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.InvNbrImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.PymtDocNbr.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PymtDocNbrImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.PymtCurrCd.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PymtCurrCdImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.PymtDate.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PymtDateImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.RodPaymentType.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.RodPaymentTypeImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.GrndTrakNbr.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.GrndTrakNbrImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.CustName.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.CustNameImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.OacPaymentType.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.OacPaymentTypeImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.PrepaidPaymentsType.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PrepaidPaymentsTypeImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.GroundPayment.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.GroundPaymentImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.OacPayments.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.OacPaymentsImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.Awb.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.AwbImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.PymtType.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PymtTypeImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.PoaDetailType.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaDetailTypeImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.PymtTotalAmt.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PymtTotalAmtImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.OtherPayments.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.OtherPaymentsImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.PymtDocType.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PymtDocTypeImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.GroundPayments.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.GroundPaymentsImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.PrepaidPaymentType.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PrepaidPaymentTypeImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.RodPayment.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.RodPaymentImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.RodPaymentsType.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.RodPaymentsTypeImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.RecCurrCd.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.RecCurrCdImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.AwbDt.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.AwbDtImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.RecTotAmt.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.RecTotAmtImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.PaymentsReceivedType.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PaymentsReceivedTypeImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.PaymentsReceived.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PaymentsReceivedImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.PymtCashAmt.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PymtCashAmtImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.GroundPaymentType.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.GroundPaymentTypeImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.OacDt.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.OacDtImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.InvCouponAmt.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.InvCouponAmtImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.PoaPaymentsType.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentsTypeImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.PoaPaymentType.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentTypeImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.AppliedTo.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.AppliedToImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.ChkAgentId.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.ChkAgentIdImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.RecDate.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.RecDateImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.OacPayment.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.OacPaymentImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.OtherPaymentsType.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.OtherPaymentsTypeImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.CourierId.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.CourierIdImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.PymtDocAmt.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PymtDocAmtImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.PoaPayments.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentsImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.PoaPayment.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.ShipDt.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.ShipDtImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.RecNbr.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.RecNbrImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.ExchRate.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.ExchRateImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.Description.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.DescriptionImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.PymtDt.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PymtDtImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.PymtTotAmt.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PymtTotAmtImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.PoaDetail.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaDetailImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.InvAmt.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.InvAmtImpl");
        defaultImplementations.put((com.fedex.lacitd.cashcontrol.interfaces.importPayments.AppliedToType.class), "com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.AppliedToTypeImpl");
        rootTagMap.put(new javax.xml.namespace.QName("", "inv_coupon_amt"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.InvCouponAmt.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "poa_payment"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.PoaPayment.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "ground_payment"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.GroundPayment.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "pymt_tot_amt"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.PymtTotAmt.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "rod_payments"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.RodPayments.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "ship_dt"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.ShipDt.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "pymt_doc_nbr"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.PymtDocNbr.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "prepaid_payment"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.PrepaidPayment.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "rec_nbr"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.RecNbr.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "rec_tot_amt"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.RecTotAmt.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "exch_rate"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.ExchRate.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "inv_nbr"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.InvNbr.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "fedex_acc_nbr"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.FedexAccNbr.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "PaymentsReceived"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.PaymentsReceived.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "pymt_doc_type"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.PymtDocType.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "pymt_date"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.PymtDate.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "ground_payments"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.GroundPayments.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "rec_rod_amt"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.RecRodAmt.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "rec_curr_cd"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.RecCurrCd.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "awb"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.Awb.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "courier_id"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.CourierId.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "oac_payment"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.OacPayment.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "rec_anc_chrg_amt"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.RecAncChrgAmt.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "pymt_type"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.PymtType.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "pymt_curr_cd"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.PymtCurrCd.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "oac_dt"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.OacDt.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "grnd_trak_nbr"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.GrndTrakNbr.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "rec_date"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.RecDate.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "pymt_total_amt"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.PymtTotalAmt.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "rod_payment"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.RodPayment.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "poa_detail"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.PoaDetail.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "pymt_cash_amt"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.PymtCashAmt.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "applied_to"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.AppliedTo.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "chk_agent_id"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.ChkAgentId.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "oac_payments"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.OacPayments.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "other_payment"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.OtherPayment.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "poa_payments"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.PoaPayments.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "pymt_doc_amt"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.PymtDocAmt.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "description"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.Description.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "pymt_dt"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.PymtDt.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "prepaid_payments"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.PrepaidPayments.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "other_payments"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.OtherPayments.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "awb_dt"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.AwbDt.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "inv_amt"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.InvAmt.class));
        rootTagMap.put(new javax.xml.namespace.QName("", "cust_name"), (com.fedex.lacitd.cashcontrol.interfaces.importPayments.CustName.class));
    }

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.fedex.lacitd.cashcontrol.interfaces.importPayments
     * 
     */
    public ObjectFactory() {
        super(grammarInfo);
    }

    /**
     * Create an instance of the specified Java content interface.
     * 
     * @param javaContentInterface
     *     the Class object of the javacontent interface to instantiate
     * @return
     *     a new instance
     * @throws JAXBException
     *     if an error occurs
     */
    public java.lang.Object newInstance(java.lang.Class javaContentInterface)
        throws javax.xml.bind.JAXBException
    {
        return super.newInstance(javaContentInterface);
    }

    /**
     * Get the specified property. This method can only be
     * used to get provider specific properties.
     * Attempting to get an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param name
     *     the name of the property to retrieve
     * @return
     *     the value of the requested property
     * @throws PropertyException
     *     when there is an error retrieving the given property or value
     */
    public java.lang.Object getProperty(java.lang.String name)
        throws javax.xml.bind.PropertyException
    {
        return super.getProperty(name);
    }

    /**
     * Set the specified property. This method can only be
     * used to set provider specific properties.
     * Attempting to set an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param value
     *     the value of the property to be set
     * @param name
     *     the name of the property to retrieve
     * @throws PropertyException
     *     when there is an error processing the given property or value
     */
    public void setProperty(java.lang.String name, java.lang.Object value)
        throws javax.xml.bind.PropertyException
    {
        super.setProperty(name, value);
    }

    /**
     * Create an instance of OtherPaymentType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.OtherPaymentType createOtherPaymentType()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.OtherPaymentTypeImpl();
    }

    /**
     * Create an instance of PrepaidPayments
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.PrepaidPayments createPrepaidPayments()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PrepaidPaymentsImpl();
    }

    /**
     * Create an instance of RecAncChrgAmt
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.RecAncChrgAmt createRecAncChrgAmt()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.RecAncChrgAmtImpl();
    }

    /**
     * Create an instance of RecAncChrgAmt
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.RecAncChrgAmt createRecAncChrgAmt(java.math.BigDecimal value)
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.RecAncChrgAmtImpl(value);
    }

    /**
     * Create an instance of RodPayments
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.RodPayments createRodPayments()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.RodPaymentsImpl();
    }

    /**
     * Create an instance of OacPaymentsType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.OacPaymentsType createOacPaymentsType()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.OacPaymentsTypeImpl();
    }

    /**
     * Create an instance of FedexAccNbr
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.FedexAccNbr createFedexAccNbr()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.FedexAccNbrImpl();
    }

    /**
     * Create an instance of FedexAccNbr
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.FedexAccNbr createFedexAccNbr(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.FedexAccNbrImpl(value);
    }

    /**
     * Create an instance of GroundPaymentsType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.GroundPaymentsType createGroundPaymentsType()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.GroundPaymentsTypeImpl();
    }

    /**
     * Create an instance of OtherPayment
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.OtherPayment createOtherPayment()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.OtherPaymentImpl();
    }

    /**
     * Create an instance of RecRodAmt
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.RecRodAmt createRecRodAmt()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.RecRodAmtImpl();
    }

    /**
     * Create an instance of RecRodAmt
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.RecRodAmt createRecRodAmt(java.math.BigDecimal value)
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.RecRodAmtImpl(value);
    }

    /**
     * Create an instance of PrepaidPayment
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.PrepaidPayment createPrepaidPayment()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PrepaidPaymentImpl();
    }

    /**
     * Create an instance of InvNbr
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.InvNbr createInvNbr()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.InvNbrImpl();
    }

    /**
     * Create an instance of InvNbr
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.InvNbr createInvNbr(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.InvNbrImpl(value);
    }

    /**
     * Create an instance of PymtDocNbr
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.PymtDocNbr createPymtDocNbr()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PymtDocNbrImpl();
    }

    /**
     * Create an instance of PymtDocNbr
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.PymtDocNbr createPymtDocNbr(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PymtDocNbrImpl(value);
    }

    /**
     * Create an instance of PymtCurrCd
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.PymtCurrCd createPymtCurrCd()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PymtCurrCdImpl();
    }

    /**
     * Create an instance of PymtCurrCd
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.PymtCurrCd createPymtCurrCd(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PymtCurrCdImpl(value);
    }

    /**
     * Create an instance of PymtDate
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.PymtDate createPymtDate()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PymtDateImpl();
    }

    /**
     * Create an instance of PymtDate
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.PymtDate createPymtDate(java.util.Calendar value)
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PymtDateImpl(value);
    }

    /**
     * Create an instance of RodPaymentType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.RodPaymentType createRodPaymentType()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.RodPaymentTypeImpl();
    }

    /**
     * Create an instance of GrndTrakNbr
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.GrndTrakNbr createGrndTrakNbr()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.GrndTrakNbrImpl();
    }

    /**
     * Create an instance of GrndTrakNbr
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.GrndTrakNbr createGrndTrakNbr(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.GrndTrakNbrImpl(value);
    }

    /**
     * Create an instance of CustName
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.CustName createCustName()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.CustNameImpl();
    }

    /**
     * Create an instance of CustName
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.CustName createCustName(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.CustNameImpl(value);
    }

    /**
     * Create an instance of OacPaymentType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.OacPaymentType createOacPaymentType()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.OacPaymentTypeImpl();
    }

    /**
     * Create an instance of PrepaidPaymentsType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.PrepaidPaymentsType createPrepaidPaymentsType()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PrepaidPaymentsTypeImpl();
    }

    /**
     * Create an instance of GroundPayment
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.GroundPayment createGroundPayment()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.GroundPaymentImpl();
    }

    /**
     * Create an instance of OacPayments
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.OacPayments createOacPayments()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.OacPaymentsImpl();
    }

    /**
     * Create an instance of Awb
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.Awb createAwb()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.AwbImpl();
    }

    /**
     * Create an instance of Awb
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.Awb createAwb(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.AwbImpl(value);
    }

    /**
     * Create an instance of PymtType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.PymtType createPymtType()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PymtTypeImpl();
    }

    /**
     * Create an instance of PymtType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.PymtType createPymtType(int value)
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PymtTypeImpl(value);
    }

    /**
     * Create an instance of PoaDetailType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.PoaDetailType createPoaDetailType()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaDetailTypeImpl();
    }

    /**
     * Create an instance of PymtTotalAmt
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.PymtTotalAmt createPymtTotalAmt()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PymtTotalAmtImpl();
    }

    /**
     * Create an instance of PymtTotalAmt
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.PymtTotalAmt createPymtTotalAmt(java.math.BigDecimal value)
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PymtTotalAmtImpl(value);
    }

    /**
     * Create an instance of OtherPayments
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.OtherPayments createOtherPayments()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.OtherPaymentsImpl();
    }

    /**
     * Create an instance of PymtDocType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.PymtDocType createPymtDocType()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PymtDocTypeImpl();
    }

    /**
     * Create an instance of PymtDocType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.PymtDocType createPymtDocType(int value)
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PymtDocTypeImpl(value);
    }

    /**
     * Create an instance of GroundPayments
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.GroundPayments createGroundPayments()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.GroundPaymentsImpl();
    }

    /**
     * Create an instance of PrepaidPaymentType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.PrepaidPaymentType createPrepaidPaymentType()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PrepaidPaymentTypeImpl();
    }

    /**
     * Create an instance of RodPayment
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.RodPayment createRodPayment()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.RodPaymentImpl();
    }

    /**
     * Create an instance of RodPaymentsType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.RodPaymentsType createRodPaymentsType()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.RodPaymentsTypeImpl();
    }

    /**
     * Create an instance of RecCurrCd
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.RecCurrCd createRecCurrCd()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.RecCurrCdImpl();
    }

    /**
     * Create an instance of RecCurrCd
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.RecCurrCd createRecCurrCd(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.RecCurrCdImpl(value);
    }

    /**
     * Create an instance of AwbDt
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.AwbDt createAwbDt()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.AwbDtImpl();
    }

    /**
     * Create an instance of AwbDt
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.AwbDt createAwbDt(java.util.Calendar value)
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.AwbDtImpl(value);
    }

    /**
     * Create an instance of RecTotAmt
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.RecTotAmt createRecTotAmt()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.RecTotAmtImpl();
    }

    /**
     * Create an instance of RecTotAmt
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.RecTotAmt createRecTotAmt(java.math.BigDecimal value)
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.RecTotAmtImpl(value);
    }

    /**
     * Create an instance of PaymentsReceivedType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.PaymentsReceivedType createPaymentsReceivedType()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PaymentsReceivedTypeImpl();
    }

    /**
     * Create an instance of PaymentsReceived
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.PaymentsReceived createPaymentsReceived()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PaymentsReceivedImpl();
    }

    /**
     * Create an instance of PymtCashAmt
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.PymtCashAmt createPymtCashAmt()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PymtCashAmtImpl();
    }

    /**
     * Create an instance of PymtCashAmt
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.PymtCashAmt createPymtCashAmt(java.math.BigDecimal value)
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PymtCashAmtImpl(value);
    }

    /**
     * Create an instance of GroundPaymentType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.GroundPaymentType createGroundPaymentType()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.GroundPaymentTypeImpl();
    }

    /**
     * Create an instance of OacDt
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.OacDt createOacDt()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.OacDtImpl();
    }

    /**
     * Create an instance of OacDt
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.OacDt createOacDt(java.util.Calendar value)
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.OacDtImpl(value);
    }

    /**
     * Create an instance of InvCouponAmt
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.InvCouponAmt createInvCouponAmt()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.InvCouponAmtImpl();
    }

    /**
     * Create an instance of InvCouponAmt
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.InvCouponAmt createInvCouponAmt(java.math.BigDecimal value)
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.InvCouponAmtImpl(value);
    }

    /**
     * Create an instance of PoaPaymentsType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.PoaPaymentsType createPoaPaymentsType()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentsTypeImpl();
    }

    /**
     * Create an instance of PoaPaymentType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.PoaPaymentType createPoaPaymentType()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentTypeImpl();
    }

    /**
     * Create an instance of AppliedTo
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.AppliedTo createAppliedTo()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.AppliedToImpl();
    }

    /**
     * Create an instance of ChkAgentId
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.ChkAgentId createChkAgentId()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.ChkAgentIdImpl();
    }

    /**
     * Create an instance of ChkAgentId
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.ChkAgentId createChkAgentId(int value)
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.ChkAgentIdImpl(value);
    }

    /**
     * Create an instance of RecDate
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.RecDate createRecDate()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.RecDateImpl();
    }

    /**
     * Create an instance of RecDate
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.RecDate createRecDate(java.util.Calendar value)
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.RecDateImpl(value);
    }

    /**
     * Create an instance of OacPayment
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.OacPayment createOacPayment()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.OacPaymentImpl();
    }

    /**
     * Create an instance of OtherPaymentsType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.OtherPaymentsType createOtherPaymentsType()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.OtherPaymentsTypeImpl();
    }

    /**
     * Create an instance of CourierId
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.CourierId createCourierId()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.CourierIdImpl();
    }

    /**
     * Create an instance of CourierId
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.CourierId createCourierId(int value)
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.CourierIdImpl(value);
    }

    /**
     * Create an instance of PymtDocAmt
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.PymtDocAmt createPymtDocAmt()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PymtDocAmtImpl();
    }

    /**
     * Create an instance of PymtDocAmt
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.PymtDocAmt createPymtDocAmt(java.math.BigDecimal value)
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PymtDocAmtImpl(value);
    }

    /**
     * Create an instance of PoaPayments
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.PoaPayments createPoaPayments()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentsImpl();
    }

    /**
     * Create an instance of PoaPayment
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.PoaPayment createPoaPayment()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaPaymentImpl();
    }

    /**
     * Create an instance of ShipDt
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.ShipDt createShipDt()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.ShipDtImpl();
    }

    /**
     * Create an instance of ShipDt
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.ShipDt createShipDt(java.util.Calendar value)
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.ShipDtImpl(value);
    }

    /**
     * Create an instance of RecNbr
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.RecNbr createRecNbr()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.RecNbrImpl();
    }

    /**
     * Create an instance of RecNbr
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.RecNbr createRecNbr(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.RecNbrImpl(value);
    }

    /**
     * Create an instance of ExchRate
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.ExchRate createExchRate()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.ExchRateImpl();
    }

    /**
     * Create an instance of ExchRate
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.ExchRate createExchRate(java.math.BigDecimal value)
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.ExchRateImpl(value);
    }

    /**
     * Create an instance of Description
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.Description createDescription()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.DescriptionImpl();
    }

    /**
     * Create an instance of Description
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.Description createDescription(java.lang.String value)
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.DescriptionImpl(value);
    }

    /**
     * Create an instance of PymtDt
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.PymtDt createPymtDt()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PymtDtImpl();
    }

    /**
     * Create an instance of PymtDt
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.PymtDt createPymtDt(java.util.Calendar value)
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PymtDtImpl(value);
    }

    /**
     * Create an instance of PymtTotAmt
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.PymtTotAmt createPymtTotAmt()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PymtTotAmtImpl();
    }

    /**
     * Create an instance of PymtTotAmt
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.PymtTotAmt createPymtTotAmt(java.math.BigDecimal value)
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PymtTotAmtImpl(value);
    }

    /**
     * Create an instance of PoaDetail
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.PoaDetail createPoaDetail()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.PoaDetailImpl();
    }

    /**
     * Create an instance of InvAmt
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.InvAmt createInvAmt()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.InvAmtImpl();
    }

    /**
     * Create an instance of InvAmt
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.InvAmt createInvAmt(java.math.BigDecimal value)
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.InvAmtImpl(value);
    }

    /**
     * Create an instance of AppliedToType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.fedex.lacitd.cashcontrol.interfaces.importPayments.AppliedToType createAppliedToType()
        throws javax.xml.bind.JAXBException
    {
        return new com.fedex.lacitd.cashcontrol.interfaces.importPayments.impl.AppliedToTypeImpl();
    }

}
