//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.2-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.03 at 04:46:07 CLT 
//


package com.fedex.lacitd.cashcontrol.interfaces.clearance.impl;

public class ReceivableImpl
    extends com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableTypeImpl
    implements com.fedex.lacitd.cashcontrol.interfaces.clearance.Receivable, com.sun.xml.bind.RIElement, com.sun.xml.bind.JAXBObject, com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.runtime.UnmarshallableObject, com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.runtime.XMLSerializable, com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.runtime.ValidatableObject
{

    public final static java.lang.Class version = (com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (com.fedex.lacitd.cashcontrol.interfaces.clearance.Receivable.class);
    }

    public java.lang.String ____jaxb_ri____getNamespaceURI() {
        return "";
    }

    public java.lang.String ____jaxb_ri____getLocalName() {
        return "receivable";
    }

    public com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.runtime.UnmarshallingEventHandler createUnmarshaller(com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.runtime.UnmarshallingContext context) {
        return new com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableImpl.Unmarshaller(context);
    }

    public void serializeBody(com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        context.startElement("", "receivable");
        super.serializeURIs(context);
        context.endNamespaceDecls();
        super.serializeAttributes(context);
        context.endAttributes();
        super.serializeBody(context);
        context.endElement();
    }

    public void serializeAttributes(com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public void serializeURIs(com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public java.lang.Class getPrimaryInterface() {
        return (com.fedex.lacitd.cashcontrol.interfaces.clearance.Receivable.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\'com.sun.msv.grammar.trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000"
+"\tnameClasst\u0000\u001fLcom/sun/msv/grammar/NameClass;xr\u0000\u001ecom.sun.msv."
+"grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000"
+"\fcontentModelt\u0000 Lcom/sun/msv/grammar/Expression;xr\u0000\u001ecom.sun."
+"msv.grammar.Expression\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0003I\u0000\u000ecachedHashCodeL\u0000\u0013epsilon"
+"Reducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000bexpandedExpq\u0000~\u0000\u0003xp5\u0018q\u00a7p"
+"p\u0000sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun."
+"msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1q\u0000~\u0000\u0003L\u0000\u0004exp2q\u0000~\u0000\u0003xq\u0000~"
+"\u0000\u00045\u0018q\u009cppsq\u0000~\u0000\u00072\u00a5|\bppsr\u0000!com.sun.msv.grammar.InterleaveExp\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\b/\u00ed{\u000fppsq\u0000~\u0000\u000b*\u008d\u00da}ppsq\u0000~\u0000\u000b\'+P\u001cppsq\u0000~\u0000\u000b$)\u00fa\u0015ppsq\u0000~"
+"\u0000\u000b \u009c\u0012\u000fppsq\u0000~\u0000\u000b\u001b\u00f5c\u00f5ppsq\u0000~\u0000\u000b\u0018\u008f)zppsq\u0000~\u0000\u000b\u0014\u00e8~\u0018ppsq\u0000~\u0000\u000b\u0010\u00ab\u00aa\u0088ppsq\u0000~"
+"\u0000\u000b\f\u00c9\u00c5Lppsq\u0000~\u0000\u000b\n\u00ae/\u0099ppsq\u0000~\u0000\u000b\u0007,\u0088\u0098ppsr\u0000\u001dcom.sun.msv.grammar.Choi"
+"ceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\b\u0002\u00c9\u00f5\u00c8ppsq\u0000~\u0000\u0000\u0002\u00c9\u00f5\u00bdsr\u0000\u0011java.lang.Boolean\u00cd"
+" r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000p\u0000sq\u0000~\u0000\u0007\u0002\u00c9\u00f5\u00b2ppsr\u0000\u001bcom.sun.msv.grammar.D"
+"ataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/relaxng/datatype/Datatype;L\u0000\u0006e"
+"xceptq\u0000~\u0000\u0003L\u0000\u0004namet\u0000\u001dLcom/sun/msv/util/StringPair;xq\u0000~\u0000\u0004\u0001\u00bd\u00c9\u00e8p"
+"psr\u0000#com.sun.msv.datatype.xsd.StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlwa"
+"ysValidxr\u0000*com.sun.msv.datatype.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.datatype.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'"
+"com.sun.msv.datatype.xsd.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespa"
+"ceUrit\u0000\u0012Ljava/lang/String;L\u0000\btypeNameq\u0000~\u0000&L\u0000\nwhiteSpacet\u0000.Lc"
+"om/sun/msv/datatype/xsd/WhiteSpaceProcessor;xpt\u0000 http://www."
+"w3.org/2001/XMLSchemat\u0000\u0006stringsr\u00005com.sun.msv.datatype.xsd.W"
+"hiteSpaceProcessor$Preserve\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.dataty"
+"pe.xsd.WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xp\u0001sr\u00000com.sun.msv.gram"
+"mar.Expression$NullSetExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0004\u0000\u0000\u0000\nppsr\u0000\u001bc"
+"om.sun.msv.util.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000&L\u0000\fnam"
+"espaceURIq\u0000~\u0000&xpq\u0000~\u0000*q\u0000~\u0000)sq\u0000~\u0000\u0018\u0001\f+\u00c5ppsr\u0000 com.sun.msv.gramma"
+"r.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0003L\u0000\tnameClassq\u0000~\u0000\u0001xq\u0000~\u0000\u0004\u0001"
+"\f+\u00baq\u0000~\u0000\u001cpsq\u0000~\u0000\u001e\u0000\u00f1\u008e\u009eppsr\u0000\"com.sun.msv.datatype.xsd.QnameType\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000#q\u0000~\u0000)t\u0000\u0005QNamesr\u00005com.sun.msv.datatype.xsd.Wh"
+"iteSpaceProcessor$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000,q\u0000~\u0000/sq\u0000~\u00000q\u0000~\u00008q"
+"\u0000~\u0000)sr\u0000#com.sun.msv.grammar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tloc"
+"alNameq\u0000~\u0000&L\u0000\fnamespaceURIq\u0000~\u0000&xr\u0000\u001dcom.sun.msv.grammar.NameC"
+"lass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpt\u0000\u0004typet\u0000)http://www.w3.org/2001/XMLSchema-"
+"instancesr\u00000com.sun.msv.grammar.Expression$EpsilonExpression"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0004\u0000\u0000\u0000\tsq\u0000~\u0000\u001b\u0001psq\u0000~\u0000<t\u0000\blocationt\u0000\u0000q\u0000~\u0000Bsq\u0000~\u0000\u0018"
+"\u0004b\u0092\u00bbppsq\u0000~\u0000\u0000\u0004b\u0092\u00b0q\u0000~\u0000\u001cp\u0000sq\u0000~\u0000\u0007\u0004b\u0092\u00a5ppq\u0000~\u0000!sq\u0000~\u0000\u0018\u0002\u00a4\u00c8\u00b8ppsq\u0000~\u00003\u0002\u00a4"
+"\u00c8\u00adq\u0000~\u0000\u001cpq\u0000~\u00005sq\u0000~\u0000<q\u0000~\u0000?q\u0000~\u0000@q\u0000~\u0000Bsq\u0000~\u0000<t\u0000\u0003mtnq\u0000~\u0000Fq\u0000~\u0000Bsq\u0000~"
+"\u0000\u0018\u0003\u0081\u00a6\u00ecppsq\u0000~\u0000\u0000\u0003\u0081\u00a6\u00e1q\u0000~\u0000\u001cp\u0000sq\u0000~\u0000\u0007\u0003\u0081\u00a6\u00d6ppq\u0000~\u0000!sq\u0000~\u0000\u0018\u0001\u00c3\u00dc\u00e9ppsq\u0000~\u00003"
+"\u0001\u00c3\u00dc\u00deq\u0000~\u0000\u001cpq\u0000~\u00005sq\u0000~\u0000<q\u0000~\u0000?q\u0000~\u0000@q\u0000~\u0000Bsq\u0000~\u0000<t\u0000\bcustomerq\u0000~\u0000Fq\u0000"
+"~\u0000Bsq\u0000~\u0000\u0018\u0002\u001b\u0095\u009eppsq\u0000~\u0000\u0000\u0002\u001b\u0095\u0093q\u0000~\u0000\u001cp\u0000sq\u0000~\u0000\u0007\u0002\u001b\u0095\u0088ppsq\u0000~\u0000\u001e\u0000\u008a\u0005Tppsr\u0000!"
+"com.sun.msv.datatype.xsd.DateType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000)com.sun.msv."
+"datatype.xsd.DateTimeBaseType\u0014W\u001a@3\u00a5\u00b4\u00e5\u0002\u0000\u0000xq\u0000~\u0000#q\u0000~\u0000)t\u0000\u0004dateq\u0000"
+"~\u0000:q\u0000~\u0000/sq\u0000~\u00000q\u0000~\u0000^q\u0000~\u0000)sq\u0000~\u0000\u0018\u0001\u0091\u0090/ppsq\u0000~\u00003\u0001\u0091\u0090$q\u0000~\u0000\u001cpq\u0000~\u00005sq\u0000"
+"~\u0000<q\u0000~\u0000?q\u0000~\u0000@q\u0000~\u0000Bsq\u0000~\u0000<t\u0000\u0007recDateq\u0000~\u0000Fq\u0000~\u0000Bsq\u0000~\u0000\u0018\u0003\u00e1\u00e5\'ppsq\u0000~"
+"\u0000\u0000\u0003\u00e1\u00e5\u001cq\u0000~\u0000\u001cp\u0000sq\u0000~\u0000\u0007\u0003\u00e1\u00e5\u0011ppq\u0000~\u0000!sq\u0000~\u0000\u0018\u0002$\u001b$ppsq\u0000~\u00003\u0002$\u001b\u0019q\u0000~\u0000\u001cpq\u0000"
+"~\u00005sq\u0000~\u0000<q\u0000~\u0000?q\u0000~\u0000@q\u0000~\u0000Bsq\u0000~\u0000<t\u0000\trecNumberq\u0000~\u0000Fq\u0000~\u0000Bsq\u0000~\u0000\u0018\u0004<"
+"\u00d3{ppsq\u0000~\u0000\u0000\u0004<\u00d3pq\u0000~\u0000\u001cp\u0000sq\u0000~\u0000\u0007\u0004<\u00d3eppq\u0000~\u0000!sq\u0000~\u0000\u0018\u0002\u007f\txppsq\u0000~\u00003\u0002\u007f\tm"
+"q\u0000~\u0000\u001cpq\u0000~\u00005sq\u0000~\u0000<q\u0000~\u0000?q\u0000~\u0000@q\u0000~\u0000Bsq\u0000~\u0000<t\u0000\u000brecCurrencyq\u0000~\u0000Fq\u0000~"
+"\u0000Bsq\u0000~\u0000\u0018\u0003\u00a6\u00abMppsq\u0000~\u0000\u0000\u0003\u00a6\u00abBq\u0000~\u0000\u001cp\u0000sq\u0000~\u0000\u0007\u0003\u00a6\u00ab7ppsq\u0000~\u0000\u001e\u0001\u00c5\u0005\u0017ppsr\u0000#c"
+"om.sun.msv.datatype.xsd.NumberType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000#q\u0000~\u0000)t\u0000\u0007d"
+"ecimalq\u0000~\u0000:q\u0000~\u0000/sq\u0000~\u00000q\u0000~\u0000{q\u0000~\u0000)sq\u0000~\u0000\u0018\u0001\u00e1\u00a6\u001bppsq\u0000~\u00003\u0001\u00e1\u00a6\u0010q\u0000~\u0000\u001cp"
+"q\u0000~\u00005sq\u0000~\u0000<q\u0000~\u0000?q\u0000~\u0000@q\u0000~\u0000Bsq\u0000~\u0000<t\u0000\bexchRateq\u0000~\u0000Fq\u0000~\u0000Bsq\u0000~\u0000\u0018\u0003"
+"f:fppsq\u0000~\u0000\u0000\u0003f:[q\u0000~\u0000\u001cp\u0000sq\u0000~\u0000\u0007\u0003f:Pppq\u0000~\u0000xsq\u0000~\u0000\u0018\u0001\u00a154ppsq\u0000~\u00003\u0001\u00a15"
+")q\u0000~\u0000\u001cpq\u0000~\u00005sq\u0000~\u0000<q\u0000~\u0000?q\u0000~\u0000@q\u0000~\u0000Bsq\u0000~\u0000<t\u0000\trecAmountq\u0000~\u0000Fq\u0000~\u0000"
+"Bsq\u0000~\u0000\u0018\u0004\u00a6\u00ae\u0005ppsq\u0000~\u0000\u0000\u0004\u00a6\u00ad\u00faq\u0000~\u0000\u001cp\u0000sq\u0000~\u0000\u0007\u0004\u00a6\u00ad\u00efppq\u0000~\u0000xsq\u0000~\u0000\u0018\u0002\u00e1\u00a8\u00d3pps"
+"q\u0000~\u00003\u0002\u00e1\u00a8\u00c8q\u0000~\u0000\u001cpq\u0000~\u00005sq\u0000~\u0000<q\u0000~\u0000?q\u0000~\u0000@q\u0000~\u0000Bsq\u0000~\u0000<t\u0000\trodAmountq"
+"\u0000~\u0000Fq\u0000~\u0000Bsq\u0000~\u0000\u0018\u0003\u008d\u00e7\u00f1ppsq\u0000~\u0000\u0000\u0003\u008d\u00e7\u00e6q\u0000~\u0000\u001cp\u0000sq\u0000~\u0000\u0007\u0003\u008d\u00e7\u00dbppq\u0000~\u0000xsq\u0000~\u0000"
+"\u0018\u0001\u00c8\u00e2\u00bfppsq\u0000~\u00003\u0001\u00c8\u00e2\u00b4q\u0000~\u0000\u001cpq\u0000~\u00005sq\u0000~\u0000<q\u0000~\u0000?q\u0000~\u0000@q\u0000~\u0000Bsq\u0000~\u0000<t\u0000\u000ean"
+"chargeAmountq\u0000~\u0000Fq\u0000~\u0000Bsq\u0000~\u0000\u0018\u0003\u0001U\u00f2ppsq\u0000~\u0000\u0000\u0003\u0001U\u00e7q\u0000~\u0000\u001cp\u0000sq\u0000~\u0000\u0007\u0003\u0001U"
+"\u00dcppq\u0000~\u0000xsq\u0000~\u0000\u0018\u0001<P\u00c0ppsq\u0000~\u00003\u0001<P\u00b5q\u0000~\u0000\u001cpq\u0000~\u00005sq\u0000~\u0000<q\u0000~\u0000?q\u0000~\u0000@q\u0000~"
+"\u0000Bsq\u0000~\u0000<t\u0000\nrecPrepAmtq\u0000~\u0000Fq\u0000~\u0000Bsq\u0000~\u0000\u0018\u0003b\u008aLppsq\u0000~\u0000\u0000\u0003b\u008aAq\u0000~\u0000\u001cp\u0000"
+"sq\u0000~\u0000\u0007\u0003b\u008a6ppq\u0000~\u0000!sq\u0000~\u0000\u0018\u0001\u00a4\u00c0Ippsq\u0000~\u00003\u0001\u00a4\u00c0>q\u0000~\u0000\u001cpq\u0000~\u00005sq\u0000~\u0000<q\u0000~\u0000"
+"?q\u0000~\u0000@q\u0000~\u0000Bsq\u0000~\u0000<t\u0000\treceiptNoq\u0000~\u0000Fq\u0000~\u0000Bsq\u0000~\u0000\u0018\u0005_\u00a0}ppsq\u0000~\u0000\u0018\u0005_\u00a0"
+"rq\u0000~\u0000\u001cpsq\u0000~\u0000\u0000\u0001\u00c5F\u008dq\u0000~\u0000\u001cp\u0000sq\u0000~\u0000\u0018\u0001\u00c5F\u0082ppsr\u0000 com.sun.msv.grammar."
+"OneOrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001ccom.sun.msv.grammar.UnaryExp\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000~\u0000\u0003xq\u0000~\u0000\u0004\u0001\u00c5Fwq\u0000~\u0000\u001cpsq\u0000~\u00003\u0001\u00c5Ftq\u0000~\u0000\u001cpsr\u00002com.sun"
+".msv.grammar.Expression$AnyStringExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0004"
+"\u0000\u0000\u0000\bq\u0000~\u0000Cpsr\u0000 com.sun.msv.grammar.AnyNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000"
+"~\u0000=q\u0000~\u0000Bsq\u0000~\u0000<t\u0000<com.fedex.lacitd.cashcontrol.interfaces.cle"
+"arance.Surchargest\u0000+http://java.sun.com/jaxb/xjc/dummy-eleme"
+"ntssq\u0000~\u0000\u0000\u0003\u009aY\u00e3q\u0000~\u0000\u001cp\u0000sq\u0000~\u0000\u0007\u0003\u009aY\u00d8ppsq\u0000~\u0000\u0000\u0001\u00c5F\u008dpp\u0000sq\u0000~\u0000\u0018\u0001\u00c5F\u0082ppsq\u0000"
+"~\u0000\u00ae\u0001\u00c5Fwq\u0000~\u0000\u001cpsq\u0000~\u00003\u0001\u00c5Ftq\u0000~\u0000\u001cpq\u0000~\u0000\u00b3q\u0000~\u0000\u00b5q\u0000~\u0000Bsq\u0000~\u0000<t\u0000@com.fed"
+"ex.lacitd.cashcontrol.interfaces.clearance.SurchargesTypeq\u0000~"
+"\u0000\u00b8sq\u0000~\u0000\u0018\u0001\u00d5\u0013Fppsq\u0000~\u00003\u0001\u00d5\u0013;q\u0000~\u0000\u001cpq\u0000~\u00005sq\u0000~\u0000<q\u0000~\u0000?q\u0000~\u0000@q\u0000~\u0000Bsq\u0000~"
+"\u0000<t\u0000\nsurchargesq\u0000~\u0000Fq\u0000~\u0000Bsq\u0000~\u0000\u0018\u0002\u00b8\u0000\u00f4ppsq\u0000~\u00003\u0002\u00b8\u0000\u00e9q\u0000~\u0000\u001cpsq\u0000~\u0000\u001e\u0001"
+"~\u00ca\u0007ppsr\u0000 com.sun.msv.datatype.xsd.IntType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000+com."
+"sun.msv.datatype.xsd.IntegerDerivedType\u0099\u00f1]\u0090&6k\u00be\u0002\u0000\u0001L\u0000\nbaseFac"
+"etst\u0000)Lcom/sun/msv/datatype/xsd/XSDatatypeImpl;xq\u0000~\u0000#q\u0000~\u0000)t\u0000"
+"\u0003intq\u0000~\u0000:sr\u0000*com.sun.msv.datatype.xsd.MaxInclusiveFacet\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000#com.sun.msv.datatype.xsd.RangeFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\nl"
+"imitValuet\u0000\u0012Ljava/lang/Object;xr\u00009com.sun.msv.datatype.xsd.D"
+"ataTypeWithValueConstraintFacet\"\u00a7Ro\u00ca\u00c7\u008aT\u0002\u0000\u0000xr\u0000*com.sun.msv.da"
+"tatype.xsd.DataTypeWithFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0005Z\u0000\fisFacetFixedZ\u0000\u0012nee"
+"dValueCheckFlagL\u0000\bbaseTypeq\u0000~\u0000\u00cbL\u0000\fconcreteTypet\u0000\'Lcom/sun/ms"
+"v/datatype/xsd/ConcreteType;L\u0000\tfacetNameq\u0000~\u0000&xq\u0000~\u0000%ppq\u0000~\u0000:\u0000\u0001"
+"sr\u0000*com.sun.msv.datatype.xsd.MinInclusiveFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000"
+"~\u0000\u00cfppq\u0000~\u0000:\u0000\u0000sr\u0000!com.sun.msv.datatype.xsd.LongType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000"
+"xq\u0000~\u0000\u00caq\u0000~\u0000)t\u0000\u0004longq\u0000~\u0000:sq\u0000~\u0000\u00ceppq\u0000~\u0000:\u0000\u0001sq\u0000~\u0000\u00d5ppq\u0000~\u0000:\u0000\u0000sr\u0000$com"
+".sun.msv.datatype.xsd.IntegerType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u00caq\u0000~\u0000)t\u0000\u0007in"
+"tegerq\u0000~\u0000:sr\u0000,com.sun.msv.datatype.xsd.FractionDigitsFacet\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001I\u0000\u0005scalexr\u0000;com.sun.msv.datatype.xsd.DataTypeWithLe"
+"xicalConstraintFacetT\u0090\u001c>\u001azb\u00ea\u0002\u0000\u0000xq\u0000~\u0000\u00d2ppq\u0000~\u0000:\u0001\u0000q\u0000~\u0000zq\u0000~\u0000zt\u0000\u000ef"
+"ractionDigits\u0000\u0000\u0000\u0000q\u0000~\u0000\u00ddt\u0000\fminInclusivesr\u0000\u000ejava.lang.Long;\u008b\u00e4\u0090\u00cc"
+"\u008f#\u00df\u0002\u0000\u0001J\u0000\u0005valuexr\u0000\u0010java.lang.Number\u0086\u00ac\u0095\u001d\u000b\u0094\u00e0\u008b\u0002\u0000\u0000xp\u0080\u0000\u0000\u0000\u0000\u0000\u0000\u0000q\u0000~\u0000\u00dd"
+"t\u0000\fmaxInclusivesq\u0000~\u0000\u00e4\u007f\u00ff\u00ff\u00ff\u00ff\u00ff\u00ff\u00ffq\u0000~\u0000\u00d8q\u0000~\u0000\u00e3sr\u0000\u0011java.lang.Integer"
+"\u0012\u00e2\u00a0\u00a4\u00f7\u0081\u00878\u0002\u0000\u0001I\u0000\u0005valuexq\u0000~\u0000\u00e5\u0080\u0000\u0000\u0000q\u0000~\u0000\u00d8q\u0000~\u0000\u00e7sq\u0000~\u0000\u00e9\u007f\u00ff\u00ff\u00ffq\u0000~\u0000/sq\u0000~\u00000"
+"q\u0000~\u0000\u00cdq\u0000~\u0000)sq\u0000~\u0000<t\u0000\u0003numq\u0000~\u0000Fq\u0000~\u0000Bsq\u0000~\u0000\u0018\u0002r\u00f5\u008fppsq\u0000~\u00003\u0002r\u00f5\u0084q\u0000~\u0000\u001cp"
+"q\u0000~\u00005sq\u0000~\u0000<q\u0000~\u0000?q\u0000~\u0000@q\u0000~\u0000Bsq\u0000~\u0000<t\u0000\nreceivableq\u0000~\u0000Fsr\u0000\"com.su"
+"n.msv.grammar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/su"
+"n/msv/grammar/ExpressionPool$ClosedHash;xpsr\u0000-com.sun.msv.gr"
+"ammar.ExpressionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0002\u0000\u0004I\u0000\u0005countI\u0000\tthresho"
+"ldL\u0000\u0006parentq\u0000~\u0000\u00f5[\u0000\u0005tablet\u0000![Lcom/sun/msv/grammar/Expression;"
+"xp\u0000\u0000\u0000<\u0000\u0000\u0000rpur\u0000![Lcom.sun.msv.grammar.Expression;\u00d68D\u00c3]\u00ad\u00a7\n\u0002\u0000\u0000x"
+"p\u0000\u0000\u0001\u007fq\u0000~\u0000oppppq\u0000~\u0000\rpppppq\u0000~\u0000}q\u0000~\u0000\u0094ppppq\u0000~\u0000Gq\u0000~\u0000\u0014pppq\u0000~\u0000mq\u0000~\u0000"
+"Jpppq\u0000~\u0000ppppppq\u0000~\u0000\u0092pppppppppppppppppppppppppppq\u0000~\u0000\u0013ppppppppp"
+"ppppppppppppppq\u0000~\u0000Qpppppppppppppppppppq\u0000~\u0000\u001dpq\u0000~\u0000Oppppq\u0000~\u0000\u000eq\u0000"
+"~\u0000Rppq\u0000~\u0000wpppq\u0000~\u0000\u0010ppppppq\u0000~\u0000\u0019ppq\u0000~\u0000\u0011q\u0000~\u0000\u0015q\u0000~\u00002pppppq\u0000~\u0000upppp"
+"ppq\u0000~\u0000\u0085pppppq\u0000~\u0000`pppppppq\u0000~\u0000\u00efpppppq\u0000~\u0000\u0017pppppppq\u0000~\u0000\u009dq\u0000~\u0000\u000fppq\u0000"
+"~\u0000Ypppppppppppppppq\u0000~\u0000\npppppq\u0000~\u0000Wppppppq\u0000~\u0000\u00c1ppppppppppq\u0000~\u0000\u00bap"
+"pq\u0000~\u0000\u0012ppppq\u0000~\u0000\u008dppq\u0000~\u0000gppppq\u0000~\u0000\u00a4ppq\u0000~\u0000\u00abppppppppppq\u0000~\u0000\u00aappq\u0000~\u0000\u0084"
+"q\u0000~\u0000epppq\u0000~\u0000\u00a2q\u0000~\u0000hpppq\u0000~\u0000\u00a5pppppppppppq\u0000~\u0000\u0082q\u0000~\u0000\fppppq\u0000~\u0000\u009cpppp"
+"ppppppq\u0000~\u0000\u0095pppq\u0000~\u0000\u0016ppppq\u0000~\u0000\u00c6pq\u0000~\u0000\u009apppppppppppppppppppppppppp"
+"pppq\u0000~\u0000\u008cpppppppppppppppppppppq\u0000~\u0000\u008appppq\u0000~\u0000\tpppppppppq\u0000~\u0000\u00b0q\u0000~"
+"\u0000\u00bdpppppppppq\u0000~\u0000Iq\u0000~\u0000\u00bcq\u0000~\u0000\u00adpp"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.runtime.UnmarshallingContext context) {
            super(context, "----");
        }

        protected Unmarshaller(com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  1 :
                        attIdx = context.getAttribute("", "num");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("surcharges" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterElement((((com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableTypeImpl)com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("surcharges" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterElement((((com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableTypeImpl)com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("receiptNo" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterElement((((com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableTypeImpl)com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("recPrepAmt" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterElement((((com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableTypeImpl)com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("anchargeAmount" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterElement((((com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableTypeImpl)com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("rodAmount" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterElement((((com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableTypeImpl)com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("recAmount" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterElement((((com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableTypeImpl)com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("exchRate" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterElement((((com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableTypeImpl)com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("recCurrency" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterElement((((com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableTypeImpl)com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("recNumber" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterElement((((com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableTypeImpl)com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("recDate" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterElement((((com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableTypeImpl)com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("customer" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterElement((((com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableTypeImpl)com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("mtn" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterElement((((com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableTypeImpl)com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("location" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterElement((((com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableTypeImpl)com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        spawnHandlerFromEnterElement((((com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableTypeImpl)com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                        return ;
                    case  0 :
                        if (("receivable" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 1;
                            return ;
                        }
                        break;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  1 :
                        attIdx = context.getAttribute("", "num");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        spawnHandlerFromLeaveElement((((com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableTypeImpl)com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname);
                        return ;
                    case  2 :
                        if (("receivable" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                    case  1 :
                        if (("num" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterAttribute((((com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableTypeImpl)com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname);
                            return ;
                        }
                        spawnHandlerFromEnterAttribute((((com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableTypeImpl)com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname);
                        return ;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                    case  1 :
                        attIdx = context.getAttribute("", "num");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        spawnHandlerFromLeaveAttribute((((com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableTypeImpl)com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname);
                        return ;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  3 :
                            revertToParentFromText(value);
                            return ;
                        case  1 :
                            attIdx = context.getAttribute("", "num");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            spawnHandlerFromText((((com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableTypeImpl)com.fedex.lacitd.cashcontrol.interfaces.clearance.impl.ReceivableImpl.this).new Unmarshaller(context)), 2, value);
                            return ;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

    }

}
