package com.fedex.lacitd.cashcontrol.biztier.facades;


/**
 * Created 18/11/2003 15:54:49
 * Code generated by the Sun ONE Studio EJB Builder
 *
 * @author ccardenas
 */

public interface PrepPoaFacadeHome extends javax.ejb.EJBHome {

    public com.fedex.lacitd.cashcontrol.biztier.facades.PrepPoaFacade create()
            throws javax.ejb.CreateException, java.rmi.RemoteException;

}
