package com.fedex.lacitd.cashcontrol.datatier.dao;

import com.fedex.lacitd.cashcontrol.datatier.exception.DAOException;

import java.util.Collection;
import java.util.List;
import java.util.Properties;
import java.util.HashMap;

/**
 * Created Nov 8, 2002 4:58:14 PM
 * Code generated by the Forte For Java EJB Builder
 *
 * @author ccardenas
 */

public interface SystemUtilsDaoLocal extends javax.ejb.EJBLocalObject {

    public int login(java.lang.String username, java.lang.String pwd) throws DAOException;

    public int login(java.lang.String username) throws DAOException;

    public Collection getCountryCurrencies(String countryCodePk) throws DAOException;

    public Properties getProperties(String category) throws DAOException;

    public String getCheckDecodeJS(String countryCd) throws DAOException;

    public void runPurgeCosmosScans() throws DAOException;
    //Miscellaneous enhancements
    public List getEmailCertificationAddresses(int role_id_nbr) throws DAOException;

    /**
     *  Method to get the URLS and roles to control access to the application
     * @return Hashmap of URLS and Roles
     * @throws com.fedex.lacitd.cashcontrol.datatier.exception.DAOException
     */
    public HashMap getUrlsAndRoles() throws DAOException;
}

