package com.fedex.lacitd.cashcontrol.datatier.dao;


/**
 * Created 10-07-2002 03:27:43 PM
 * Code generated by the Forte For Java EJB Builder
 *
 * @author ccardenas
 */

public interface RODDaoHome extends javax.ejb.EJBHome {

    public RODDao create() throws javax.ejb.CreateException, java.rmi.RemoteException;

}
