package com.fedex.lacitd.cashcontrol.datatier.dao;

import com.fedex.lacitd.cashcontrol.datatier.exception.DAOException;

import java.rmi.RemoteException;
import java.util.Properties;
import java.util.HashMap;

/**
 * Created Nov 8, 2002 4:58:14 PM
 * Code generated by the Forte For Java EJB Builder
 *
 * @author ccardenas
 */

public interface SystemUtilsDao extends javax.ejb.EJBObject {

    public int login(String username, String pwd) throws java.rmi.RemoteException, DAOException;

    public int login(String username) throws java.rmi.RemoteException, DAOException;

    public java.util.Collection getCountryCurrencies(String countryCodePk) throws java.rmi.RemoteException, DAOException;

    public Properties getProperties(String category) throws java.rmi.RemoteException, DAOException;

    public String getCheckDecodeJS(String countryCd) throws java.rmi.RemoteException, DAOException;

    public void runPurgeCosmosScans() throws DAOException, RemoteException;

    /**
     *  Method to get the URLS and roles to control access to the application
     * @return Hashmap of URLS and Roles
     * @throws com.fedex.lacitd.cashcontrol.datatier.exception.DAOException
     */
    public HashMap getUrlsAndRoles() throws DAOException, RemoteException;
}

